# Generated by Django 3.0.6 on 2020-06-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.TextField(default='Anonymous'),
        ),
    ]
