# Generated by Django 3.0.6 on 2020-06-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_remove_message_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default='2000-06-03 03:08:50.262391'),
        ),
    ]
