# Generated by Django 3.0.6 on 2020-06-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_message_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('imglink', models.TextField(blank=True, default='', null=True)),
                ('admin_approved', models.BooleanField(default='False')),
            ],
        ),
    ]
